id: AC8520C44
title: Aspiration to Be Reborn at the Vajra Seat (Bodhgayā), Akaniṣṭha on Earth
type: translation
pechas:
- IC999835E
- I38A33D00
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:50.738513
  last_modified_at: 2023-01-04 12:06:50.738524
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IC999835E/4DEC: 5A2C
  I38A33D00/994F: 5A2C
